### ISSUE TITLE
Lexer

### ISSUE THREAD

**Issue by arexon** [sedgeland/gnalom#1]
## Description

A lexer to tokenize MoLang expressions that will then be fed into the parser.

## Tasks

- [x] Tokenize numeric values like `2` or `0.5`
- [x] Tokenize string literals like `'minecraft:sheep'`
- [x] Tokenize name literals like `math.sin` or `query.health`
- [x] Tokenize single characters i.e. `+` or `{`
- [x] Ignore line comments
